{
	"version": 1754033111,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/peakmeter.png",
		"images/frequencybin.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/kipas-sheet0.png",
		"images/tiangkipas-sheet0.png",
		"images/saklar-sheet0.png",
		"images/lampu-sheet0.png",
		"images/lampu-sheet1.png",
		"images/tombol1-sheet0.png",
		"images/tombol2-sheet0.png",
		"images/generatortangan-sheet0.png",
		"images/tombol3-sheet0.png",
		"images/batrai1-sheet0.png",
		"images/batrai2-sheet0.png",
		"images/wadahbatrai-sheet0.png",
		"images/bondarieskiri-sheet0.png",
		"images/bondarieskanan-sheet0.png",
		"images/tombol4-sheet0.png",
		"images/turbinair-sheet0.png",
		"images/particles.png",
		"images/tombol5-sheet0.png",
		"images/saklarputar-sheet0.png",
		"images/rangkaian-sheet0.png",
		"images/tombol6-sheet0.png",
		"images/gunung-sheet0.png",
		"images/sensorsolar-sheet0.png",
		"images/matahari-sheet0.png",
		"images/batasmatahari-sheet0.png",
		"images/tanah-sheet0.png",
		"images/tombol7-sheet0.png",
		"images/accu-sheet0.png",
		"images/botolaccu-sheet0.png",
		"images/lobangaccu1-sheet0.png",
		"images/isiaccu-sheet0.png",
		"images/tombol8-sheet0.png",
		"images/tombolkiri-sheet0.png",
		"images/tombolkiri-sheet1.png",
		"images/spritefontinfobawah.png",
		"images/spritefontinfoatas.png",
		"images/tandapanahkanan-sheet0.png",
		"images/tandapanahkanan-sheet1.png",
		"images/tombolbermai2n-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tapis-sheet0.png",
		"images/logouniversitasteknokrat-sheet0.png",
		"images/logokemdikbud-sheet0.png",
		"images/logomedukasi-sheet0.png",
		"images/simoki-sheet0.png",
		"images/lamk-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tombolback-sheet0.png",
		"images/tombol_teorii-sheet0.png",
		"images/tombolbermai2n2-sheet0.png",
		"images/tombolinfo-sheet0.png",
		"images/logo-sheet0.png",
		"images/tombolmedukasi-sheet0.png",
		"images/tombolsound_off-sheet0.png",
		"images/tombolsound_off-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/gematik-sheet0.png",
		"images/balingbalingttengah-sheet0.png",
		"images/lampuceklistrik-sheet0.png",
		"images/lampuceklistrik-sheet1.png",
		"images/kincirairdepan-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/pipan-sheet0.png",
		"images/djsetat-sheet0.png",
		"images/speakerajat-sheet0.png",
		"images/speakerajat-sheet1.png",
		"images/cloudlayerb-sheet0.png",
		"images/cloudlayerb2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/lamputamanoff-sheet0.png",
		"images/spritefontinfoatas3.png",
		"images/plywood-sheet0.png",
		"images/kabel-sheet0.png",
		"images/kabelsambungkananl-sheet0.png",
		"images/kabelsambungkananl-sheet1.png",
		"images/spritefontinfoatas4.png",
		"images/logorumahbelajar-sheet0.png",
		"media/firstsong.ogg",
		"media/firstsong.m4a",
		"media/1. percobaan virtual listrik.m4a",
		"media/1. percobaan virtual listrik.ogg",
		"media/2. praktik.ogg",
		"media/3. belajar.ogg",
		"media/4. mulai.ogg",
		"media/materi 1 kincir2.ogg",
		"media/materi 2 charger.ogg",
		"media/materi4 batrai.ogg",
		"media/materi4 dinamo2.ogg",
		"media/materi5 kincir.ogg",
		"media/materi6 saklar.ogg",
		"media/materi7 matahari.ogg",
		"media/materi8 aki.ogg",
		"media/soundforlayout7.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"adapter.js"
	]
}